//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynovaExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributeCenter
    {
        public int Id { get; set; }
        public int ShipmentID { get; set; }
        public int UserID { get; set; }
        public int DriverID { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual User User { get; set; }
        public virtual Shipment Shipment { get; set; }
    }
}
